plugins:
  - '@semantic-release/commit-analyzer':
      preset: "angular"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "perf"
          release: "patch"
        - type: "chore"
          release: "patch"
        - type: "docs"
          release: "patch"
        - type: "revert"
          release: "patch"
        - breaking: true
          release: "major"
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
