version: "3"
services:

  fuseki:
    user: root
    image: "ghcr.io/zazuko/fuseki-geosparql:4.8.0"
    ports:
      - "3030:3030"
    volumes:
      - type: bind
        source: ${PWD}/../dev/dev-config.ttl
        target: /fuseki/config.ttl
    environment:
      ADMIN_PASSWORD: pw
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3030 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s

  prez:
    image: "ghcr.io/rdflib/prez:latest"
    ports:
      - "8000:8000"
    environment:
      SPARQL_ENDPOINT: 'http://fuseki:3030/sp'
    depends_on:
      fuseki:
        condition: service_healthy
