version: "3"
services:

  fuseki:
    user: root
    image: "ghcr.io/zazuko/fuseki-geosparql:4.6.0"  # recommend using the Zazuko repo to build a 4.7.0 image.
    ports:
      - "3030:3030"
    volumes:
      - type: bind
        source: ${PWD}/../dev/dev-config.ttl
        target: /fuseki/config.ttl
    environment:
      ADMIN_PASSWORD: pw
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://fuseki:3030" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 20s

  prez:
    image: "ghcr.io/rdflib/prez:3.0.6"
    ports:
      - "8000:8000"
    environment:
      SPACEPREZ_SPARQL_ENDPOINT: 'http://fuseki:3030/sp'
      VOCPREZ_SPARQL_ENDPOINT: 'http://fuseki:3030/vp'
      CATPREZ_SPARQL_ENDPOINT: 'http://fuseki:3030/cp'
    depends_on:
      fuseki:
        condition: service_healthy
