PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX void: <http://rdfs.org/ns/void#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
CONSTRUCT {
    ?focusNode ?fp1 ?fo .
    ?fs ?fp2 ?focusNode .
	?fo_bn ?fo_bnp ?fo_bno .
    ?fo_bn2 ?fo_bn2p ?fo_bn2o .
    ?m ?mp1 ?mo .
    ?ms ?mp2 ?m .
    ?mo_bn2 ?mp_bn2 ?mo_bn2o .
    ?mo_bn ?mp_bn ?mo_bno .
}
WHERE {
    VALUES ?focusNode { UNDEF }
#    VALUES ?dataset { UNDEF }
    ?focusNode void:inDataset ?dataset .
    ?focusNode ?fp1 ?fo .
    OPTIONAL {
        ?fs ?fp2 ?focusNode .
    }
    OPTIONAL {
        ?focusNode ?fp1 ?fo_bn .
        FILTER(isBLANK(?fo_bn))
        ?fo_bn ?fo_bnp ?fo_bno .
        OPTIONAL {
            ?fo_bn ?fo_bnp ?fo_bn2 .
            FILTER(isBLANK(?fo_bn2))
            ?fo_bn2 ?fo_bn2p ?fo_bn2o .
        }
    }
    ?focusNode rdfs:member ?m .
    ?m ?mp1 ?mo .
    OPTIONAL {
        ?ms ?mp2 ?m .
    }
    OPTIONAL {
        ?m ?mp1 ?mo_bn .
        FILTER (isBLANK(?mo_bn))
        ?mo_bn ?mp_bn ?mo_bno .
        OPTIONAL {
            ?mo_bn ?mp_bn ?mo_bn2 .
            FILTER (isBlank(?mo_bn2))
            ?mo_bn2 ?mp_bn2 ?mo_bn2o .
        }
    }
} LIMIT 1000  # refactor out